import { test, expect } from "../fixtures/base-fixture.js"

test.describe('OrangeHRM Employee Test', () => {

    test('verify add valid employee', async ({ page }) => {
        await page.locator("xpath=//input[@name='username']").fill("Admin")
        await page.locator("xpath=//input[@name='password']").fill("admin123")
        await page.locator("xpath=//button[normalize-space()='Login']").click()
        // # click on PIM Menu
        // # click on Add Employee
        // # enter firstname as john
        // # enter middlename as m
        // # enter lastname as wick
        // # click on save
        // # verify the profile name - john wick
        // # verify the textbox first name - john

        // # note employee id is autogenerated sometimes it fails because of concurrent user. just rerun if run fails.
    });


})